### ISSUE TITLE
Don't store single IP in a set

### ISSUE THREAD

**Issue by Yoda-BZH** [ansibleguy/infra_nftables#1]
When defining a single ip in a variable, the variable in nftables is always declared in a set.

This is [to be avoided](https://wiki.nftables.org/wiki-nftables/index.php/Scripting#Defining_variables), and forbids the use of some rules.

For example, I have a single IP:

```
nftables:
  _defaults:  # defaults inherited by all tables and chains
    table:
      type: 'inet'
      vars:
        host_myserver_ip: "192.0.2.1"
```

If I want to do some prerouting:
```

nftables_custom:
  tables:
    my_filter:
      chains:
        myprerouting:
          hook: 'prerouting'
          priority: dstnat
          type: 'nat'
          policy: 'accept'
            - proto: tcp
              dport: 2200
              src: "192.0.2.2"
              "dnat to": '$host_myserver_ip:22'
```

The result will be:
```
    tcp dport 2200 ip saddr "192.0.2.2" dnat to $host_myserver_ip:22
```

But since $host_myserver_ip is a set, `{ 192.0.2.1 }:22` is not permitted.

When nft configtest is ran, I have the error:
```
/tmp/nftables_my_filter.nft:92:36-53: Error: you cannot use a set here, unknown value to use
  define host_myserver_ip = { 192.0.2.1 }
```
I suppose it is nft's way to say that using a set in `dnat to` with a `host:port` is not possible.

Variables are always forced to a list in https://github.com/ansibleguy/infra_nftables/blob/43ceabf3071391fd403a22534fa181a12a1353b0/filter_plugins/rules.py#L36

Would it be possible to check the value, if a string, use a string variable, else use a set ?

Thank you

OS: Ubuntu 20.04 LTS
